use super::abi_blocks::additional_abi_blocks;
use super::*;

pub(super) fn ui_block_catalog() -> Vec<UiBlockDefinition> {
    let mut blocks = vec![
        UiBlockDefinition {
            id: "const_string",
            title: "Const String",
            category: "value",
            description: "Create a string variable output for downstream blocks.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "text_value",
                    placeholder: "text_value",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "hello",
                    placeholder: "hello",
                    connectable: false,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "const_number",
            title: "Const Number",
            category: "value",
            description: "Create a number variable output for downstream blocks.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "num_value",
                    placeholder: "num_value",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Number,
                    default_value: "1",
                    placeholder: "1",
                    connectable: false,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_header",
            title: "Get Header",
            category: "http_request",
            description: "Read request header into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "header",
                    placeholder: "header",
                    connectable: false,
                },
                UiBlockInput {
                    key: "name",
                    label: "Header Name",
                    input_type: UiInputType::Text,
                    default_value: "x-client-id",
                    placeholder: "x-client-id",
                    connectable: false,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_headers",
            title: "Get Request Headers",
            category: "http_request",
            description: "Read all request headers into a map variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_headers",
                placeholder: "request_headers",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_query_arg",
            title: "Get Query Arg",
            category: "http_request",
            description: "Read one query parameter value into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "query_value",
                    placeholder: "query_value",
                    connectable: false,
                },
                UiBlockInput {
                    key: "name",
                    label: "Query Name",
                    input_type: UiInputType::Text,
                    default_value: "id",
                    placeholder: "id",
                    connectable: false,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_query_args",
            title: "Get Query Args",
            category: "http_request",
            description: "Read all query parameters into a map variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "query_args",
                placeholder: "query_args",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_id",
            title: "Get Request ID",
            category: "http_request",
            description: "Read request id into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_id",
                placeholder: "request_id",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_method",
            title: "Get Request Method",
            category: "http_request",
            description: "Read request method into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_method",
                placeholder: "request_method",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_path",
            title: "Get Request Path",
            category: "http_request",
            description: "Read request path into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_path",
                placeholder: "request_path",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_query",
            title: "Get Request Query",
            category: "http_request",
            description: "Read request query into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_query",
                placeholder: "request_query",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_path_with_query",
            title: "Get Path+Query",
            category: "http_request",
            description: "Read request path and query into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_path_with_query",
                placeholder: "request_path_with_query",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_scheme",
            title: "Get Request Scheme",
            category: "http_request",
            description: "Read request scheme into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_scheme",
                placeholder: "request_scheme",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_http_version",
            title: "Get HTTP Version",
            category: "http_request",
            description: "Read request HTTP version into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_http_version",
                placeholder: "request_http_version",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_port",
            title: "Get Request Port",
            category: "http_request",
            description: "Read request port into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_port",
                placeholder: "request_port",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_body",
            title: "Get Request Body",
            category: "http_request",
            description: "Read request body into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_body",
                placeholder: "request_body",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_body_next_chunk",
            title: "Get Request Body Chunk",
            category: "http_request",
            description: "Read the next request body chunk into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "request_chunk",
                    placeholder: "request_chunk",
                    connectable: false,
                },
                UiBlockInput {
                    key: "max_bytes",
                    label: "Max Bytes",
                    input_type: UiInputType::Number,
                    default_value: "1024",
                    placeholder: "1024 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_body_eof",
            title: "Get Request Body EOF",
            category: "http_request",
            description: "Read whether request body stream reached EOF into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_body_eof",
                placeholder: "request_body_eof",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_host",
            title: "Get Request Host",
            category: "http_request",
            description: "Read request host into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "request_host",
                placeholder: "request_host",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_request_client_ip",
            title: "Get Client IP",
            category: "http_request",
            description: "Read request client ip into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "client_ip",
                placeholder: "client_ip",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "string_concat",
            title: "String Concat",
            category: "string",
            description: "Concatenate two string expressions into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "joined_text",
                    placeholder: "joined_text",
                    connectable: false,
                },
                UiBlockInput {
                    key: "left",
                    label: "Left",
                    input_type: UiInputType::Text,
                    default_value: "hello ",
                    placeholder: "hello or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "right",
                    label: "Right",
                    input_type: UiInputType::Text,
                    default_value: "world",
                    placeholder: "world or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "string_length",
            title: "String Length",
            category: "string",
            description: "Measure string length into a number variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "text_len",
                    placeholder: "text_len",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "hello",
                    placeholder: "hello or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "string_slice",
            title: "String Slice",
            category: "string",
            description: "Slice string by range and store into a variable (supports [:end], [start:], and negative end).",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "text_slice",
                    placeholder: "text_slice",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "hello",
                    placeholder: "hello or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "start",
                    label: "Start",
                    input_type: UiInputType::Number,
                    default_value: "0",
                    placeholder: "0, -1, or $var (empty for start)",
                    connectable: true,
                },
                UiBlockInput {
                    key: "end",
                    label: "End",
                    input_type: UiInputType::Number,
                    default_value: "3",
                    placeholder: "3, -1, or $var (empty for end)",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "math_add",
            title: "Math Add",
            category: "math",
            description: "Add two numbers and store the result in a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "math_sum",
                    placeholder: "math_sum",
                    connectable: false,
                },
                UiBlockInput {
                    key: "lhs",
                    label: "Left",
                    input_type: UiInputType::Number,
                    default_value: "1",
                    placeholder: "1 or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "rhs",
                    label: "Right",
                    input_type: UiInputType::Number,
                    default_value: "1",
                    placeholder: "1 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "math_subtract",
            title: "Math Subtract",
            category: "math",
            description: "Subtract right number from left number.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "math_diff",
                    placeholder: "math_diff",
                    connectable: false,
                },
                UiBlockInput {
                    key: "lhs",
                    label: "Left",
                    input_type: UiInputType::Number,
                    default_value: "1",
                    placeholder: "1 or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "rhs",
                    label: "Right",
                    input_type: UiInputType::Number,
                    default_value: "1",
                    placeholder: "1 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "math_multiply",
            title: "Math Multiply",
            category: "math",
            description: "Multiply two numbers and store the result.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "math_product",
                    placeholder: "math_product",
                    connectable: false,
                },
                UiBlockInput {
                    key: "lhs",
                    label: "Left",
                    input_type: UiInputType::Number,
                    default_value: "2",
                    placeholder: "2 or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "rhs",
                    label: "Right",
                    input_type: UiInputType::Number,
                    default_value: "2",
                    placeholder: "2 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "math_divide",
            title: "Math Divide",
            category: "math",
            description: "Divide left number by right number.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "math_quotient",
                    placeholder: "math_quotient",
                    connectable: false,
                },
                UiBlockInput {
                    key: "lhs",
                    label: "Left",
                    input_type: UiInputType::Number,
                    default_value: "4",
                    placeholder: "4 or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "rhs",
                    label: "Right",
                    input_type: UiInputType::Number,
                    default_value: "2",
                    placeholder: "2 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "array_new",
            title: "Array New",
            category: "collection",
            description: "Create an empty array variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "items",
                placeholder: "items",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "array_push",
            title: "Array Push",
            category: "collection",
            description: "Append a value to an array and output the updated array.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "items_next",
                    placeholder: "items_next",
                    connectable: false,
                },
                UiBlockInput {
                    key: "array",
                    label: "Array",
                    input_type: UiInputType::Text,
                    default_value: "$items",
                    placeholder: "$items",
                    connectable: true,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "item",
                    placeholder: "item or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "array_get",
            title: "Array Get",
            category: "collection",
            description: "Read array index into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "item_value",
                    placeholder: "item_value",
                    connectable: false,
                },
                UiBlockInput {
                    key: "array",
                    label: "Array",
                    input_type: UiInputType::Text,
                    default_value: "$items",
                    placeholder: "$items",
                    connectable: true,
                },
                UiBlockInput {
                    key: "index",
                    label: "Index",
                    input_type: UiInputType::Number,
                    default_value: "0",
                    placeholder: "0 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "array_set",
            title: "Array Set",
            category: "collection",
            description: "Set array index and output the updated array.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "items_next",
                    placeholder: "items_next",
                    connectable: false,
                },
                UiBlockInput {
                    key: "array",
                    label: "Array",
                    input_type: UiInputType::Text,
                    default_value: "$items",
                    placeholder: "$items",
                    connectable: true,
                },
                UiBlockInput {
                    key: "index",
                    label: "Index",
                    input_type: UiInputType::Number,
                    default_value: "0",
                    placeholder: "0 or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "item",
                    placeholder: "item or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "map_new",
            title: "Map New",
            category: "collection",
            description: "Create an empty map variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "map_value",
                placeholder: "map_value",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "map_get",
            title: "Map Get",
            category: "collection",
            description: "Read map key into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "map_item",
                    placeholder: "map_item",
                    connectable: false,
                },
                UiBlockInput {
                    key: "map",
                    label: "Map",
                    input_type: UiInputType::Text,
                    default_value: "$map_value",
                    placeholder: "$map_value",
                    connectable: true,
                },
                UiBlockInput {
                    key: "key",
                    label: "Key",
                    input_type: UiInputType::Text,
                    default_value: "key",
                    placeholder: "key or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "map_set",
            title: "Map Set",
            category: "collection",
            description: "Set map key and output the updated map.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "map_next",
                    placeholder: "map_next",
                    connectable: false,
                },
                UiBlockInput {
                    key: "map",
                    label: "Map",
                    input_type: UiInputType::Text,
                    default_value: "$map_value",
                    placeholder: "$map_value",
                    connectable: true,
                },
                UiBlockInput {
                    key: "key",
                    label: "Key",
                    input_type: UiInputType::Text,
                    default_value: "key",
                    placeholder: "key or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "value",
                    placeholder: "value or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "set_request_header",
            title: "Set Upstream Request Header",
            category: "http_upstream_request",
            description: "Set outbound request header via the default upstream exchange wrapper.",
            inputs: vec![
                UiBlockInput {
                    key: "name",
                    label: "Header Name",
                    input_type: UiInputType::Text,
                    default_value: "x-added",
                    placeholder: "x-added",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "1",
                    placeholder: "1 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "add_request_header",
            title: "Add Upstream Request Header",
            category: "http_upstream_request",
            description: "Append outbound request header via the default upstream exchange wrapper.",
            inputs: vec![
                UiBlockInput {
                    key: "name",
                    label: "Header Name",
                    input_type: UiInputType::Text,
                    default_value: "x-added",
                    placeholder: "x-added",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "1",
                    placeholder: "1 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "clear_request_header",
            title: "Clear Upstream Request Header",
            category: "http_upstream_request",
            description: "Clear outbound request header via the default upstream exchange wrapper.",
            inputs: vec![UiBlockInput {
                key: "name",
                label: "Header Name",
                input_type: UiInputType::Text,
                default_value: "x-remove",
                placeholder: "x-remove",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_request_method",
            title: "Set Upstream Request Method",
            category: "http_upstream_request",
            description: "Set outbound request method via the default upstream exchange wrapper.",
            inputs: vec![UiBlockInput {
                key: "method",
                label: "Method",
                input_type: UiInputType::Text,
                default_value: "GET",
                placeholder: "GET or $var",
                connectable: true,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_request_path",
            title: "Set Upstream Request Path",
            category: "http_upstream_request",
            description: "Set outbound request path via the default upstream exchange wrapper.",
            inputs: vec![UiBlockInput {
                key: "path",
                label: "Path",
                input_type: UiInputType::Text,
                default_value: "/",
                placeholder: "/new-path or $var",
                connectable: true,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_request_query",
            title: "Set Upstream Request Query",
            category: "http_upstream_request",
            description: "Set outbound request query via the default upstream exchange wrapper.",
            inputs: vec![UiBlockInput {
                key: "query",
                label: "Query",
                input_type: UiInputType::Text,
                default_value: "x=1",
                placeholder: "x=1 or $var",
                connectable: true,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_request_query_arg",
            title: "Set Upstream Query Arg",
            category: "http_upstream_request",
            description: "Set one outbound request query argument.",
            inputs: vec![
                UiBlockInput {
                    key: "name",
                    label: "Query Name",
                    input_type: UiInputType::Text,
                    default_value: "id",
                    placeholder: "id",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "1",
                    placeholder: "1 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_request_body",
            title: "Set Upstream Request Body",
            category: "http_upstream_request",
            description: "Set outbound request body via the default upstream exchange wrapper.",
            inputs: vec![UiBlockInput {
                key: "value",
                label: "Body",
                input_type: UiInputType::Text,
                default_value: "payload",
                placeholder: "payload or $var",
                connectable: true,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_header",
            title: "Set Header",
            category: "http_response",
            description: "Set response header via vm.http.response.set_header.",
            inputs: vec![
                UiBlockInput {
                    key: "name",
                    label: "Header Name",
                    input_type: UiInputType::Text,
                    default_value: "x-vm",
                    placeholder: "x-vm",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "ok",
                    placeholder: "ok or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "add_response_header",
            title: "Add Response Header",
            category: "http_response",
            description: "Append response header via vm.http.response.add_header.",
            inputs: vec![
                UiBlockInput {
                    key: "name",
                    label: "Header Name",
                    input_type: UiInputType::Text,
                    default_value: "set-cookie",
                    placeholder: "set-cookie",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "a=1",
                    placeholder: "a=1 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "clear_response_header",
            title: "Clear Response Header",
            category: "http_response",
            description: "Clear response header via vm.http.response.clear_header.",
            inputs: vec![UiBlockInput {
                key: "name",
                label: "Header Name",
                input_type: UiInputType::Text,
                default_value: "x-remove",
                placeholder: "x-remove",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_response_content",
            title: "Set Response Content",
            category: "http_response",
            description: "Short-circuit request with response content.",
            inputs: vec![UiBlockInput {
                key: "value",
                label: "Body",
                input_type: UiInputType::Text,
                default_value: "okkk",
                placeholder: "request allowed or $var",
                connectable: true,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "set_response_status",
            title: "Set Response Status",
            category: "http_response",
            description: "Set response status code (used for short-circuit and upstream responses).",
            inputs: vec![UiBlockInput {
                key: "status",
                label: "Status Code",
                input_type: UiInputType::Number,
                default_value: "429",
                placeholder: "200-599",
                connectable: true,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "get_response_status",
            title: "Get Response Status",
            category: "http_response",
            description: "Read response status into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "response_status",
                placeholder: "response_status",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_response_header",
            title: "Get Response Header",
            category: "http_response",
            description: "Read response header into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "response_header",
                    placeholder: "response_header",
                    connectable: false,
                },
                UiBlockInput {
                    key: "name",
                    label: "Header Name",
                    input_type: UiInputType::Text,
                    default_value: "x-vm",
                    placeholder: "x-vm",
                    connectable: false,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_response_headers",
            title: "Get Response Headers",
            category: "http_response",
            description: "Read all response headers into a map variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "response_headers",
                placeholder: "response_headers",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_response_body",
            title: "Get Response Body",
            category: "http_response",
            description: "Read response body into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "response_body",
                placeholder: "response_body",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_upstream_response_status",
            title: "Get Upstream Response Status",
            category: "http_upstream_response",
            description: "Read upstream response status into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "upstream_status",
                placeholder: "upstream_status",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_upstream_response_header",
            title: "Get Upstream Response Header",
            category: "http_upstream_response",
            description: "Read upstream response header into a variable.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "upstream_header",
                    placeholder: "upstream_header",
                    connectable: false,
                },
                UiBlockInput {
                    key: "name",
                    label: "Header Name",
                    input_type: UiInputType::Text,
                    default_value: "x-upstream",
                    placeholder: "x-upstream",
                    connectable: false,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_upstream_response_headers",
            title: "Get Upstream Response Headers",
            category: "http_upstream_response",
            description: "Read all upstream response headers into a map variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "upstream_headers",
                placeholder: "upstream_headers",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "get_upstream_response_body",
            title: "Get Upstream Response Body",
            category: "http_upstream_response",
            description: "Read upstream response body into a variable.",
            inputs: vec![UiBlockInput {
                key: "var",
                label: "Variable",
                input_type: UiInputType::Text,
                default_value: "upstream_body",
                placeholder: "upstream_body",
                connectable: false,
            }],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "json_encode",
            title: "JSON Encode",
            category: "json",
            description: "Encode a value to JSON text.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "json_text",
                    placeholder: "json_text",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "Value",
                    input_type: UiInputType::Text,
                    default_value: "$payload",
                    placeholder: "$payload or literal",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "json_decode",
            title: "JSON Decode",
            category: "json",
            description: "Decode JSON text into a value.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "json_value",
                    placeholder: "json_value",
                    connectable: false,
                },
                UiBlockInput {
                    key: "value",
                    label: "JSON Text",
                    input_type: UiInputType::Text,
                    default_value: "$json_text",
                    placeholder: "$json_text or literal",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "set_upstream",
            title: "Set Upstream",
            category: "routing",
            description: "Forward request to the upstream host and port via the default upstream exchange wrapper.",
            inputs: vec![
                UiBlockInput {
                    key: "host",
                    label: "Host",
                    input_type: UiInputType::Text,
                    default_value: "127.0.0.1",
                    placeholder: "127.0.0.1",
                    connectable: true,
                },
                UiBlockInput {
                    key: "port",
                    label: "Port",
                    input_type: UiInputType::Number,
                    default_value: "8088",
                    placeholder: "8088",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "runtime_sleep",
            title: "Runtime Sleep",
            category: "runtime",
            description: "Sleep runtime VM execution for a number of milliseconds via vm.runtime.sleep.",
            inputs: vec![UiBlockInput {
                key: "millis",
                label: "Milliseconds",
                input_type: UiInputType::Number,
                default_value: "10",
                placeholder: "10 or $var",
                connectable: true,
            }],
            outputs: vec![UiBlockOutput {
                key: "next",
                label: "next",
                expr_from_input: None,
            }],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "rate_limit_allow",
            title: "Rate Limit Allow",
            category: "control",
            description: "Evaluate vm.rate_limit.allow and store a boolean result.",
            inputs: vec![
                UiBlockInput {
                    key: "var",
                    label: "Variable",
                    input_type: UiInputType::Text,
                    default_value: "rate_allowed",
                    placeholder: "rate_allowed",
                    connectable: false,
                },
                UiBlockInput {
                    key: "key_expr",
                    label: "Key Expr",
                    input_type: UiInputType::Text,
                    default_value: "$header",
                    placeholder: "$header or literal",
                    connectable: true,
                },
                UiBlockInput {
                    key: "limit",
                    label: "Limit",
                    input_type: UiInputType::Number,
                    default_value: "3",
                    placeholder: "3 or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "window_seconds",
                    label: "Window Seconds",
                    input_type: UiInputType::Number,
                    default_value: "60",
                    placeholder: "60 or $var",
                    connectable: true,
                },
            ],
            outputs: vec![UiBlockOutput {
                key: "value",
                label: "value",
                expr_from_input: Some("var"),
            }],
            accepts_flow: false,
        },
        UiBlockDefinition {
            id: "rate_limit_if_else",
            title: "Rate Limit If/Else",
            category: "control",
            description: "Use vm.rate_limit.allow and branch to allowed/blocked flow outputs.",
            inputs: vec![
                UiBlockInput {
                    key: "key_expr",
                    label: "Key Expr",
                    input_type: UiInputType::Text,
                    default_value: "$header",
                    placeholder: "$header or literal",
                    connectable: true,
                },
                UiBlockInput {
                    key: "limit",
                    label: "Limit",
                    input_type: UiInputType::Number,
                    default_value: "3",
                    placeholder: "3",
                    connectable: false,
                },
                UiBlockInput {
                    key: "window_seconds",
                    label: "Window Seconds",
                    input_type: UiInputType::Number,
                    default_value: "60",
                    placeholder: "60",
                    connectable: false,
                },
            ],
            outputs: vec![
                UiBlockOutput {
                    key: "allowed",
                    label: "allowed",
                    expr_from_input: None,
                },
                UiBlockOutput {
                    key: "blocked",
                    label: "blocked",
                    expr_from_input: None,
                },
            ],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "if",
            title: "If",
            category: "control",
            description: "Plain conditional compare with true/false flow outputs.",
            inputs: vec![
                UiBlockInput {
                    key: "lhs",
                    label: "LHS",
                    input_type: UiInputType::Text,
                    default_value: "left",
                    placeholder: "left or $var",
                    connectable: true,
                },
                UiBlockInput {
                    key: "rhs",
                    label: "RHS",
                    input_type: UiInputType::Text,
                    default_value: "right",
                    placeholder: "right or $var",
                    connectable: true,
                },
            ],
            outputs: vec![
                UiBlockOutput {
                    key: "true",
                    label: "true",
                    expr_from_input: None,
                },
                UiBlockOutput {
                    key: "false",
                    label: "false",
                    expr_from_input: None,
                },
            ],
            accepts_flow: true,
        },
        UiBlockDefinition {
            id: "loop",
            title: "Loop",
            category: "control",
            description: "Plain fixed-count loop with body/done flow outputs.",
            inputs: vec![UiBlockInput {
                key: "count",
                label: "Count",
                input_type: UiInputType::Number,
                default_value: "1",
                placeholder: "1 or $var",
                connectable: true,
            }],
            outputs: vec![
                UiBlockOutput {
                    key: "body",
                    label: "body",
                    expr_from_input: None,
                },
                UiBlockOutput {
                    key: "done",
                    label: "done",
                    expr_from_input: None,
                },
            ],
            accepts_flow: true,
        },
    ];
    blocks.extend(additional_abi_blocks());
    blocks
}
