//! Canonical host-schema parsing shared by the `pd-host-function` proc macro
//! and the `pd-vm` build script.
//!
//! Both expansion paths must agree on how resource parameters are recognized
//! (the `ResourceRef` / `ResourceMut` / `ResourceOwned` wrappers plus the
//! `#[pd_host_param(passing = ..., key = ...)]` family of attributes), how the
//! resulting schema labels look, and which resource type keys are legal.
//! Centralizing those rules here guarantees that the descriptor generated by
//! the proc macro (ordered label / schema / passing / key) can never drift
//! from the descriptor the build script computes for the same signature.
//!
//! The crate is deliberately runtime-free (only `syn`/`proc-macro2`): it is
//! linked by a `proc-macro` crate and by a `build.rs`, neither of which can
//! depend on the VM.

use std::fmt;

use syn::{Attribute, GenericArgument, LitStr, Meta, PathArguments, Type};

/// Maximum byte length of a validated resource type key.
///
/// This mirrors `pd_vm::host_api`'s `MAX_RESOURCE_KEY_LEN`; the proc macro and
/// the build script reject keys at expansion time with the exact same rules
/// the runtime applies, so an invalid key can never reach a runtime
/// `.expect()` panic.
pub const MAX_RESOURCE_KEY_LEN: usize = 128;

/// Why a resource type key literal is invalid.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ResourceKeyError {
    Empty,
    TooLong(usize),
    InvalidChar { index: usize, ch: char },
    InvalidDotPlacement { index: usize },
}

impl fmt::Display for ResourceKeyError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Empty => write!(f, "resource type key must not be empty"),
            Self::TooLong(len) => write!(
                f,
                "resource type key is {len} bytes; the maximum is {MAX_RESOURCE_KEY_LEN}"
            ),
            Self::InvalidChar { index, ch } => write!(
                f,
                "resource type key contains invalid character {ch:?} at byte offset {index}"
            ),
            Self::InvalidDotPlacement { index } => write!(
                f,
                "resource type key contains an empty namespace segment at byte offset {index}"
            ),
        }
    }
}

impl std::error::Error for ResourceKeyError {}

/// Validates a resource type key with the same rules as
/// `pd_vm::host_api::ResourceTypeKey::new`.
pub fn validate_resource_key(name: &str) -> Result<(), ResourceKeyError> {
    if name.is_empty() {
        return Err(ResourceKeyError::Empty);
    }
    if name.len() > MAX_RESOURCE_KEY_LEN {
        return Err(ResourceKeyError::TooLong(name.len()));
    }
    // Allowed: ASCII lowercase a-z, 0-9, '_' and '-', with '.' used purely as
    // a namespace separator between non-empty segments.
    for (index, b) in name.bytes().enumerate() {
        let valid = b.is_ascii_lowercase() || b.is_ascii_digit() || matches!(b, b'_' | b'-' | b'.');
        if !valid {
            return Err(ResourceKeyError::InvalidChar {
                index,
                ch: name[index..].chars().next().unwrap_or('\u{fffd}'),
            });
        }
    }
    // Report the exact byte offset of each empty segment: a '.' that directly
    // follows another '.' (or the leading dot) opens an empty segment at that
    // dot, and a trailing '.' leaves an empty segment at the end of the name.
    let mut segment_start = 0usize;
    for (index, b) in name.bytes().enumerate() {
        if b == b'.' {
            if index == segment_start {
                return Err(ResourceKeyError::InvalidDotPlacement { index });
            }
            segment_start = index + 1;
        }
    }
    if segment_start == name.len() {
        return Err(ResourceKeyError::InvalidDotPlacement {
            index: segment_start,
        });
    }
    Ok(())
}

/// The four resource passing modes the adapter layer understands.
///
/// `to_owned` is **not** a host passing mode: a guest-side `to_owned()`
/// expression is ordinary `Value` passing, and asking the adapter for a
/// resource-containing `to_owned` frame is rejected with an explicit
/// "reserved" error instead of being silently aliased to `Value` or
/// `TakeOwned`.
///
/// This mirrors `pd_vm::vm::resource::ResourceAccessMode`; it is kept
/// runtime-free here so both the proc macro and the build script can share the
/// parsing rules.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ResourceMode {
    Borrow,
    BorrowMut,
    TakeOwned,
    Value,
}

/// The coarse host-parameter passing categories emitted into catalog metadata.
/// This mirrors `pd_vm::host_api::HostParamPassing`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum HostPassing {
    Value,
    Borrow,
    BorrowMut,
    TakeOwned,
}

impl fmt::Display for HostPassing {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            Self::Value => "value",
            Self::Borrow => "borrow",
            Self::BorrowMut => "borrow_mut",
            Self::TakeOwned => "take_owned",
        })
    }
}

impl ResourceMode {
    /// Normalizes and parses a `passing = "..."` string literal.
    ///
    /// `to_owned` / `toowned` are explicitly **reserved**: they return an error
    /// naming the reserved mode rather than silently aliasing it to `Value` or
    /// `TakeOwned`.
    pub fn parse(value: &str) -> Result<Self, String> {
        let normalized = value.to_ascii_lowercase().replace('-', "_");
        match normalized.as_str() {
            "borrow" => Ok(Self::Borrow),
            "borrow_mut" | "borrowmut" => Ok(Self::BorrowMut),
            "take_owned" | "takeowned" | "owned" => Ok(Self::TakeOwned),
            "to_owned" | "toowned" => Err(
                "to_owned passing is reserved and unsupported; use take_owned to transfer \
                 resource ownership"
                    .to_string(),
            ),
            "value" => Ok(Self::Value),
            _ => {
                Err("resource passing must be borrow, borrow_mut, take_owned, or value".to_string())
            }
        }
    }

    /// The catalog passing category. There is no host `ToOwned` category: the
    /// only non-resource category is `Value`.
    pub fn host_passing(self) -> HostPassing {
        match self {
            Self::Borrow => HostPassing::Borrow,
            Self::BorrowMut => HostPassing::BorrowMut,
            Self::TakeOwned => HostPassing::TakeOwned,
            Self::Value => HostPassing::Value,
        }
    }

    /// Whether accessing this mode consumes the resource slot.
    pub const fn is_consuming(self) -> bool {
        matches!(self, Self::TakeOwned)
    }
}

/// Schema label used for a resource parameter or return (mirrors the proc
/// macro's `"resource"` label and the runtime `HostTypeSchema::Resource`).
pub const RESOURCE_SCHEMA_LABEL: &str = "resource";

/// Parsed resource parameter/return metadata.
#[derive(Clone, Debug)]
pub struct ResourceSpec {
    /// The resolved passing mode (from the canonical wrapper or the attribute).
    pub mode: ResourceMode,
    /// The concrete resource type. For canonical wrappers this is the wrapper's
    /// type argument; for annotation-only declarations it is the declared type.
    pub inner: Type,
    /// Whether the declaration used a canonical owning wrapper (`ResourceOwned`).
    pub owned_wrapper: bool,
    /// An explicit `key = "..."` literal if one was declared. Already validated.
    pub key: Option<String>,
}

/// Kind of a resource *return* type. Only the owned `Resource<T>` wrapper may
/// cross the host boundary; borrowed wrappers must be rejected by callers.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ResourceReturnKind {
    /// `Resource<T>` — an owned handle token.
    Owned,
    /// `ResourceRef<'_, T>` — a borrow that must not cross the boundary.
    Borrow,
    /// `ResourceMut<'_, T>` — a mutable borrow that must not cross the boundary.
    BorrowMut,
}

/// Unwraps grouping/parenthesized surface syntax.
fn unwrap_surface(ty: &Type) -> &Type {
    let mut current = ty;
    loop {
        current = match current {
            Type::Group(group) => &group.elem,
            Type::Paren(paren) => &paren.elem,
            other => return other,
        };
    }
}

/// The final path segment identifier of the surface type, if it is a path.
pub fn path_last_ident(ty: &Type) -> Option<String> {
    let ty = unwrap_surface(ty);
    let Type::Path(path) = ty else {
        return None;
    };
    path.path
        .segments
        .last()
        .map(|segment| segment.ident.to_string())
}

/// Parses the resource-passing attributes on a parameter into an explicit mode
/// and an explicit key. Mirrors the proc macro's `parse_resource_attrs`.
pub fn parse_resource_attrs(
    attrs: &[Attribute],
) -> Result<(Option<ResourceMode>, Option<String>), String> {
    let mut mode = None;
    let mut key = None;
    for attr in attrs {
        let path = attr.path();
        if path.is_ident("pd_borrow") {
            mode = Some(ResourceMode::Borrow);
            continue;
        }
        if path.is_ident("pd_borrow_mut") {
            mode = Some(ResourceMode::BorrowMut);
            continue;
        }
        if path.is_ident("pd_take_owned") {
            mode = Some(ResourceMode::TakeOwned);
            continue;
        }
        if path.is_ident("pd_to_owned") {
            return Err(
                "pd_to_owned is reserved and unsupported; use pd_take_owned to transfer \
                 resource ownership"
                    .to_string(),
            );
        }
        if path.is_ident("pd_value") {
            mode = Some(ResourceMode::Value);
            continue;
        }
        if !(path.is_ident("pd_host_param")
            || path.is_ident("pd_host_resource")
            || path.is_ident("pd_host_passing"))
        {
            continue;
        }
        match &attr.meta {
            Meta::Path(_) => {}
            Meta::NameValue(name_value) => {
                let syn::Expr::Lit(expr_lit) = &name_value.value else {
                    return Err("resource passing metadata must be a string literal".to_string());
                };
                let syn::Lit::Str(value) = &expr_lit.lit else {
                    return Err("resource passing metadata must be a string literal".to_string());
                };
                if name_value.path.is_ident("passing") || path.is_ident("pd_host_passing") {
                    mode = Some(ResourceMode::parse(value.value().as_str())?);
                } else if name_value.path.is_ident("key") {
                    key = Some(value.value());
                } else {
                    return Err("expected passing = \"...\" or key = \"...\"".to_string());
                }
            }
            Meta::List(_) => {
                attr.parse_nested_meta(|nested| {
                    if nested.path.is_ident("borrow") {
                        mode = Some(ResourceMode::Borrow);
                        return Ok(());
                    }
                    if nested.path.is_ident("borrow_mut") || nested.path.is_ident("borrowmut") {
                        mode = Some(ResourceMode::BorrowMut);
                        return Ok(());
                    }
                    if nested.path.is_ident("take_owned")
                        || nested.path.is_ident("takeowned")
                        || nested.path.is_ident("owned")
                    {
                        mode = Some(ResourceMode::TakeOwned);
                        return Ok(());
                    }
                    if nested.path.is_ident("to_owned") || nested.path.is_ident("toowned") {
                        return Err(nested.error(
                            "to_owned is reserved and unsupported; use take_owned to transfer \
                             resource ownership",
                        ));
                    }
                    if nested.path.is_ident("value") {
                        mode = Some(ResourceMode::Value);
                        return Ok(());
                    }
                    if nested.path.is_ident("passing") {
                        let value: LitStr = nested.value()?.parse()?;
                        mode = Some(
                            ResourceMode::parse(value.value().as_str())
                                .map_err(|msg| syn::Error::new(value.span(), msg))?,
                        );
                        return Ok(());
                    }
                    if nested.path.is_ident("key") {
                        key = Some(nested.value()?.parse::<LitStr>()?.value());
                        return Ok(());
                    }
                    Err(nested.error(
                        "expected a resource passing mode, passing = \"...\", or key = \"...\"",
                    ))
                })
                .map_err(|err| err.to_string())?;
            }
        }
    }
    Ok((mode, key))
}

/// The canonical resource wrapper names that the adapter can expand reliably.
pub const CANONICAL_WRAPPERS: [&str; 3] = ["ResourceRef", "ResourceMut", "ResourceOwned"];

/// Whether `ident` names a canonical resource wrapper.
pub fn is_canonical_wrapper(ident: &str) -> bool {
    matches!(ident, "ResourceRef" | "ResourceMut" | "ResourceOwned")
}

/// Extracts the single concrete type argument of a path segment (the last type
/// argument, so a `ResourceRef<'_, T>` lifetime prefix is skipped).
pub fn generic_type_argument(segment: &syn::PathSegment) -> Result<Type, String> {
    let syn::PathArguments::AngleBracketed(args) = &segment.arguments else {
        return Err("resource wrapper requires one concrete resource type".to_string());
    };
    args.args
        .iter()
        .rev()
        .find_map(|arg| match arg {
            GenericArgument::Type(ty) => Some(ty.clone()),
            _ => None,
        })
        .ok_or_else(|| "resource wrapper requires one concrete resource type".to_string())
}

/// Parses one parameter into resource metadata, or `None` for an ordinary
/// parameter. This is the single canonical rule used by both the proc macro
/// and the build script, so their descriptors can never diverge.
///
/// Errors are plain messages; the proc macro re-spans them onto the parameter
/// type and the build script turns them into build failures.
pub fn resource_spec(ty: &Type, attrs: &[Attribute]) -> Result<Option<ResourceSpec>, String> {
    let (explicit_mode, key) = parse_resource_attrs(attrs)?;
    let wrapper = path_last_ident(ty);
    let Some(wrapper) = wrapper else {
        return if explicit_mode.is_some() {
            Err("resource passing metadata requires a concrete resource type".to_string())
        } else {
            Ok(None)
        };
    };
    let inferred = match wrapper.as_str() {
        "ResourceRef" => Some((ResourceMode::Borrow, true)),
        "ResourceMut" => Some((ResourceMode::BorrowMut, true)),
        "ResourceOwned" => Some((ResourceMode::TakeOwned, true)),
        _ => None,
    };
    let Some((inferred_mode, owned_wrapper)) =
        inferred.or_else(|| explicit_mode.map(|mode| (mode, false)))
    else {
        return Ok(None);
    };
    let mode = explicit_mode.unwrap_or(inferred_mode);
    if explicit_mode.is_some() && inferred.is_some() && mode != inferred_mode {
        return Err("resource wrapper and passing metadata specify different modes".to_string());
    }
    if matches!(mode, ResourceMode::Value) {
        return Err(
            "resource-containing Value parameters are rejected; use Borrow, BorrowMut, or TakeOwned"
                .to_string(),
        );
    }
    // An explicit annotation on a bare identifier is a concrete resource type
    // (e.g. `#[pd_host_param(passing = "take_owned")] r: FakeResource`). A
    // path that carries generic arguments or a qualified prefix cannot be a
    // concrete `HostResource` type and is almost always a type alias to a
    // resource wrapper, which the macro cannot resolve reliably.
    if explicit_mode.is_some() && inferred.is_none() {
        let path = match unwrap_surface(ty) {
            Type::Path(path) => path,
            _ => unreachable!("path_last_ident only yields for path types"),
        };
        let has_suspicious_shape = path.path.segments.len() > 1
            || matches!(
                path.path.segments.last().map(|s| &s.arguments),
                Some(PathArguments::AngleBracketed(_) | PathArguments::Parenthesized(_))
            );
        if has_suspicious_shape {
            return Err(
                "resource passing metadata on an alias/unqualified wrapper path is not supported; use a canonical ResourceRef, ResourceMut, or ResourceOwned wrapper or a bare concrete resource type"
                    .to_string(),
            );
        }
    }
    let inner = if inferred.is_some() {
        let Type::Path(path) = unwrap_surface(ty) else {
            unreachable!("canonical wrapper is a path type")
        };
        generic_type_argument(
            path.path
                .segments
                .last()
                .expect("canonical resource wrapper segment"),
        )?
    } else {
        (*ty).clone()
    };
    if let Some(key) = &key {
        validate_resource_key(key).map_err(|error| error.to_string())?;
    }
    Ok(Some(ResourceSpec {
        mode,
        inner,
        owned_wrapper,
        key,
    }))
}

/// Converts a supported Rust type syntax into the canonical host-schema label.
///
/// This parser is shared by the proc macro and the root build script. It
/// intentionally returns strings so the runtime-free schema crate can be used
/// by both compilation phases without depending on the VM's schema model.
pub fn type_label(ty: &Type) -> Result<String, String> {
    match ty {
        Type::Group(group) => type_label(&group.elem),
        Type::Paren(paren) => type_label(&paren.elem),
        Type::Reference(reference) => type_label(&reference.elem),
        Type::Slice(slice) => match slice.elem.as_ref() {
            Type::Path(path) if path.path.segments.last().is_some_and(|s| s.ident == "u8") => {
                Ok("bytes".to_string())
            }
            _ => Err("unsupported callable type".to_string()),
        },
        Type::Tuple(tuple) if tuple.elems.is_empty() => Ok("null".to_string()),
        Type::Path(path) => {
            let Some(segment) = path.path.segments.last() else {
                return Err("unsupported callable type".to_string());
            };
            let ident = segment.ident.to_string();
            match ident.as_str() {
                "i8" | "i16" | "i32" | "i64" | "i128" | "isize" | "u8" | "u16" | "u32" | "u64"
                | "u128" | "usize" => Ok("int".to_string()),
                "f32" | "f64" => Ok("float".to_string()),
                "bool" => Ok("bool".to_string()),
                "String" | "str" | "VmStringRef" => Ok("string".to_string()),
                "Bytes" | "VmBytes" | "VmBytesRef" | "VmBytesHandle" => Ok("bytes".to_string()),
                "Any" | "AnyValue" | "Value" | "VmValueRef" | "VmValueOwned" => {
                    Ok("any".to_string())
                }
                "Array" | "VmArray" | "VmArrayRef" | "VmArrayHandle" => Ok("array".to_string()),
                "Map" | "VmMap" | "VmMapRef" | "VmMapHandle" => Ok("map".to_string()),
                "Number" | "NumberValue" => Ok("number".to_string()),
                "Resource" | "ResourceRef" | "ResourceMut" => Ok(RESOURCE_SCHEMA_LABEL.to_string()),
                "ResourceOwned" => Err(
                    "ResourceOwned is input-only; it cannot be used as a return schema".to_string(),
                ),
                "VmCallable" => callable_type_label(segment),
                "Unknown" | "UnknownValue" => Ok("unknown".to_string()),
                "CallOutcome" => Ok("unknown".to_string()),
                "Option" => {
                    let args = one_type_argument(segment, "Option")?;
                    Ok(format!("{} | null", type_label(args)?))
                }
                "VmResult" | "HostCallResult" | "HostFutureOutput" => {
                    let args = one_type_argument(segment, &ident)?;
                    type_label(args)
                }
                "Vec" => type_label_for_vec(segment),
                _ => Err(format!("unsupported callable type '{ident}'")),
            }
        }
        _ => Err("unsupported callable type".to_string()),
    }
}

/// Returns a canonical type label and whether the parameter is an `Option<T>`,
/// honoring resource-passing attributes on concrete types.
pub fn parameter_type_label_with_attrs(
    ty: &Type,
    attrs: &[Attribute],
) -> Result<(String, bool), String> {
    if resource_spec(ty, attrs)?.is_some() {
        return Ok((RESOURCE_SCHEMA_LABEL.to_string(), false));
    }
    parameter_type_label_inner(ty)
}

/// Returns a canonical type label and whether the parameter is an `Option<T>`.
pub fn parameter_type_label(ty: &Type) -> Result<(String, bool), String> {
    parameter_type_label_with_attrs(ty, &[])
}

fn parameter_type_label_inner(ty: &Type) -> Result<(String, bool), String> {
    let optional = path_last_ident(ty).as_deref() == Some("Option");
    Ok((type_label(ty)?, optional))
}

fn one_type_argument<'a>(segment: &'a syn::PathSegment, name: &str) -> Result<&'a Type, String> {
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        return Err(format!("{name}<T> requires one generic argument"));
    };
    let Some(GenericArgument::Type(inner)) = args.args.first() else {
        return Err(format!("{name}<T> requires one type argument"));
    };
    if args.args.len() != 1 {
        return Err(format!("{name}<T> requires one generic argument"));
    }
    Ok(inner)
}

fn callable_type_label(segment: &syn::PathSegment) -> Result<String, String> {
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        return Err("VmCallable requires a function signature".to_string());
    };
    let Some(GenericArgument::Type(Type::BareFn(function))) = args.args.first() else {
        return Err("VmCallable requires fn(...) -> ...".to_string());
    };
    if args.args.len() != 1 {
        return Err("VmCallable requires one function signature".to_string());
    }
    let params = function
        .inputs
        .iter()
        .map(|input| type_label(&input.ty))
        .collect::<Result<Vec<_>, _>>()?;
    let result = match &function.output {
        syn::ReturnType::Default => "null".to_string(),
        syn::ReturnType::Type(_, ty) => type_label(ty)?,
    };
    Ok(format!("fn({}) -> {result}", params.join(", ")))
}

fn type_label_for_vec(segment: &syn::PathSegment) -> Result<String, String> {
    let inner = one_type_argument(segment, "Vec")?;
    match inner {
        Type::Tuple(tuple) if tuple.elems.len() == 2 => {
            let lhs = tuple
                .elems
                .first()
                .expect("two-element tuple has a first element");
            let rhs = tuple
                .elems
                .last()
                .expect("two-element tuple has a last element");
            if is_value_type(lhs) && is_value_type(rhs) {
                Ok("map".to_string())
            } else {
                Err("unsupported Vec tuple type in callable metadata".to_string())
            }
        }
        _ if is_value_type(inner) => Ok("array".to_string()),
        _ => {
            let inner_label = type_label(inner)?;
            Err(format!("unsupported Vec return type '{inner_label}'"))
        }
    }
}

fn is_value_type(ty: &Type) -> bool {
    match ty {
        Type::Group(group) => is_value_type(&group.elem),
        Type::Paren(paren) => is_value_type(&paren.elem),
        Type::Reference(reference) => is_value_type(&reference.elem),
        Type::Path(path) => path
            .path
            .segments
            .last()
            .is_some_and(|segment| segment.ident == "Value"),
        _ => false,
    }
}

/// Classifies a *return* type as an owned `Resource<T>` token, a borrowed
/// `ResourceRef<'_, T>`, or a `ResourceMut<'_, T>`. Returns `None` for anything
/// that is not a resource wrapper.
pub fn resource_return_kind(ty: &Type) -> Option<ResourceReturnKind> {
    let ident = path_last_ident(ty)?;
    match ident.as_str() {
        "Resource" => Some(ResourceReturnKind::Owned),
        "ResourceRef" => Some(ResourceReturnKind::Borrow),
        "ResourceMut" => Some(ResourceReturnKind::BorrowMut),
        _ => None,
    }
}

/// A borrowed resource wrapper found while walking a host function return type.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct BorrowedResourceReturn {
    /// The borrowed wrapper that cannot cross the host boundary.
    pub kind: ResourceReturnKind,
    /// Transparent return wrappers from the outermost type to the resource.
    pub wrappers: Vec<String>,
}

/// Finds a borrowed resource wrapper nested inside supported return wrappers.
///
/// `VmResult<T>`, `Result<T, E>`, `Option<T>`, `HostCallResult<T>`, and
/// `HostFutureOutput<T>` are transparent for this validation. The traversal is
/// deliberately independent of the final schema label so a borrowed resource
/// cannot be hidden behind a wrapper that would otherwise be flattened by the
/// host-function parser.
pub fn borrowed_resource_return(ty: &Type) -> Option<BorrowedResourceReturn> {
    let ty = unwrap_return_surface(ty);
    if let Some(kind) = resource_return_kind(ty) {
        return match kind {
            ResourceReturnKind::Borrow | ResourceReturnKind::BorrowMut => {
                Some(BorrowedResourceReturn {
                    kind,
                    wrappers: Vec::new(),
                })
            }
            ResourceReturnKind::Owned => None,
        };
    }

    let Type::Path(path) = ty else {
        return None;
    };
    let segment = path.path.segments.last()?;
    let wrapper = segment.ident.to_string();
    if !matches!(
        wrapper.as_str(),
        "VmResult" | "Result" | "Option" | "HostCallResult" | "HostFutureOutput"
    ) {
        return None;
    }
    let PathArguments::AngleBracketed(args) = &segment.arguments else {
        return None;
    };
    for argument in &args.args {
        let GenericArgument::Type(inner) = argument else {
            continue;
        };
        let Some(mut found) = borrowed_resource_return(inner) else {
            continue;
        };
        found.wrappers.insert(0, wrapper.clone());
        return Some(found);
    }
    None
}

fn unwrap_return_surface(ty: &Type) -> &Type {
    let mut current = ty;
    loop {
        current = match current {
            Type::Group(group) => &group.elem,
            Type::Paren(paren) => &paren.elem,
            Type::Reference(reference) => &reference.elem,
            other => return other,
        };
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use syn::parse_quote;

    #[test]
    fn key_validation_matches_expected_rules() {
        assert!(validate_resource_key("io.file").is_ok());
        assert!(validate_resource_key("file").is_ok());
        assert!(validate_resource_key("a-b.c_0").is_ok());
        assert_eq!(validate_resource_key(""), Err(ResourceKeyError::Empty));
        assert!(matches!(
            validate_resource_key("Io.File").unwrap_err(),
            ResourceKeyError::InvalidChar { .. }
        ));
        assert!(matches!(
            validate_resource_key("io..file").unwrap_err(),
            ResourceKeyError::InvalidDotPlacement { .. }
        ));
        assert!(matches!(
            validate_resource_key(".io.file").unwrap_err(),
            ResourceKeyError::InvalidDotPlacement { .. }
        ));
        assert!(matches!(
            validate_resource_key("io.file.").unwrap_err(),
            ResourceKeyError::InvalidDotPlacement { .. }
        ));
        let overlong = "a".repeat(MAX_RESOURCE_KEY_LEN + 1);
        assert!(matches!(
            validate_resource_key(&overlong).unwrap_err(),
            ResourceKeyError::TooLong(len) if len == MAX_RESOURCE_KEY_LEN + 1
        ));
    }

    #[test]
    fn canonical_wrappers_infer_modes() {
        let ty: Type = parse_quote!(ResourceRef<'_, FakeResource>);
        let spec = resource_spec(&ty, &[]).unwrap().expect("resource");
        assert_eq!(spec.mode, ResourceMode::Borrow);
        assert!(spec.owned_wrapper);

        let ty: Type = parse_quote!(ResourceMut<'_, FakeResource>);
        let spec = resource_spec(&ty, &[]).unwrap().expect("resource");
        assert_eq!(spec.mode, ResourceMode::BorrowMut);

        let ty: Type = parse_quote!(ResourceOwned<FakeResource>);
        let spec = resource_spec(&ty, &[]).unwrap().expect("resource");
        assert_eq!(spec.mode, ResourceMode::TakeOwned);
        assert!(spec.owned_wrapper);
    }

    #[test]
    fn ordinary_parameters_are_not_resources() {
        let ty: Type = parse_quote!(i64);
        assert!(resource_spec(&ty, &[]).unwrap().is_none());
        let ty: Type = parse_quote!(String);
        assert!(resource_spec(&ty, &[]).unwrap().is_none());
    }

    #[test]
    fn explicit_annotation_on_concrete_type_is_supported() {
        let ty: Type = parse_quote!(FakeResource);
        let attrs: Vec<Attribute> =
            parse_quote!(#[pd_host_param(passing = "take_owned", key = "test.fake")]);
        let spec = resource_spec(&ty, &attrs).unwrap().expect("resource");
        assert_eq!(spec.mode, ResourceMode::TakeOwned);
        assert_eq!(spec.key.as_deref(), Some("test.fake"));
        assert!(!spec.owned_wrapper);
    }

    #[test]
    fn annotation_mode_conflict_is_rejected() {
        let ty: Type = parse_quote!(ResourceOwned<FakeResource>);
        let attrs: Vec<Attribute> = parse_quote!(#[pd_host_param(passing = "borrow")]);
        let error = resource_spec(&ty, &attrs).unwrap_err();
        assert!(error.contains("different modes"), "{error}");
    }

    #[test]
    fn to_owned_and_value_resource_modes_are_rejected() {
        // `to_owned` / `toowned` are reserved at parse time (never aliased to
        // Value or TakeOwned): the literal, the attribute, and the nested form
        // all fail with an explicit "reserved" error.
        for literal in ["to_owned", "toowned", "TO_OWNED"] {
            let error = ResourceMode::parse(literal).expect_err("to_owned must be reserved");
            assert!(error.contains("reserved"), "{literal}: {error}");
        }
        let ty: Type = parse_quote!(FakeResource);
        let attrs: Vec<Attribute> = parse_quote!(#[pd_host_param(passing = "to_owned")]);
        let error = resource_spec(&ty, &attrs).unwrap_err();
        assert!(error.contains("reserved"), "{error}");
        let attrs: Vec<Attribute> = parse_quote!(#[pd_to_owned]);
        let error = resource_spec(&ty, &attrs).unwrap_err();
        assert!(error.contains("reserved"), "{error}");
        let attrs: Vec<Attribute> = parse_quote!(#[pd_host_passing(to_owned)]);
        let error = resource_spec(&ty, &attrs).unwrap_err();
        assert!(error.contains("reserved"), "{error}");

        // `value` on a resource type is rejected by the spec (not reserved).
        let ty: Type = parse_quote!(FakeResource);
        let attrs: Vec<Attribute> = parse_quote!(#[pd_host_param(passing = "value")]);
        let error = resource_spec(&ty, &attrs).unwrap_err();
        assert!(error.contains("Value"), "{error}");
        assert!(error.contains("rejected"), "{error}");
    }

    #[test]
    fn invalid_explicit_keys_are_rejected_at_parse_time() {
        let ty: Type = parse_quote!(FakeResource);
        for key in ["", "bad key", "io..file", "A.b"] {
            let attrs: Vec<Attribute> =
                parse_quote!(#[pd_host_param(passing = "take_owned", key = #key)]);
            let error = resource_spec(&ty, &attrs).unwrap_err();
            assert!(error.contains("resource type key"), "{error}");
        }
    }

    #[test]
    fn alias_wrapper_shape_with_annotation_is_rejected() {
        // A path whose final segment is a canonical wrapper is a qualified
        // (e.g. re-exported) canonical wrapper and is fully supported.
        let ty: Type = parse_quote!(my_alias::ResourceRef<'static, FakeResource>);
        let attrs: Vec<Attribute> = parse_quote!(#[pd_host_param(passing = "borrow")]);
        let spec = resource_spec(&ty, &attrs)
            .unwrap()
            .expect("qualified wrapper");
        assert_eq!(spec.mode, ResourceMode::Borrow);

        // A non-canonical path that carries a qualified prefix or generic
        // arguments cannot be a concrete `HostResource` type and is almost
        // always an alias the parser cannot expand reliably.
        let ty: Type = parse_quote!(my_alias::Wrapper<'static, FakeResource>);
        let error = resource_spec(&ty, &attrs).unwrap_err();
        assert!(error.contains("alias"), "{error}");

        let ty: Type = parse_quote!(WrapperAlias<FakeResource>);
        let error = resource_spec(&ty, &attrs).unwrap_err();
        assert!(error.contains("alias"), "{error}");
    }

    #[test]
    fn resource_return_kinds_are_classified() {
        let ty: Type = parse_quote!(Resource<FakeResource>);
        assert_eq!(resource_return_kind(&ty), Some(ResourceReturnKind::Owned));
        let ty: Type = parse_quote!(ResourceRef<'_, FakeResource>);
        assert_eq!(resource_return_kind(&ty), Some(ResourceReturnKind::Borrow));
        let ty: Type = parse_quote!(ResourceMut<'_, FakeResource>);
        assert_eq!(
            resource_return_kind(&ty),
            Some(ResourceReturnKind::BorrowMut)
        );
        let ty: Type = parse_quote!(i64);
        assert_eq!(resource_return_kind(&ty), None);
    }

    #[test]
    fn borrowed_resource_return_shape_recurses_transparent_wrappers() {
        let ty: Type = parse_quote!(VmResult<ResourceRef<'static, FakeResource>>);
        let found = borrowed_resource_return(&ty).expect("borrowed resource");
        assert_eq!(found.kind, ResourceReturnKind::Borrow);
        assert_eq!(found.wrappers, vec!["VmResult"]);

        let ty: Type = parse_quote!(Option<ResourceMut<'static, FakeResource>>);
        let found = borrowed_resource_return(&ty).expect("borrowed mutable resource");
        assert_eq!(found.kind, ResourceReturnKind::BorrowMut);
        assert_eq!(found.wrappers, vec!["Option"]);

        let ty: Type = parse_quote!(Result<Option<ResourceRef<'static, FakeResource>>, FakeError>);
        let found = borrowed_resource_return(&ty).expect("nested borrowed resource");
        assert_eq!(found.kind, ResourceReturnKind::Borrow);
        assert_eq!(found.wrappers, vec!["Result", "Option"]);

        let ty: Type = parse_quote!(VmResult<Option<Resource<FakeResource>>>);
        assert!(borrowed_resource_return(&ty).is_none());
    }

    #[test]
    fn host_passing_mapping_matches_the_runtime() {
        assert_eq!(ResourceMode::Borrow.host_passing(), HostPassing::Borrow);
        assert_eq!(
            ResourceMode::BorrowMut.host_passing(),
            HostPassing::BorrowMut
        );
        assert_eq!(
            ResourceMode::TakeOwned.host_passing(),
            HostPassing::TakeOwned
        );
        assert_eq!(ResourceMode::Value.host_passing(), HostPassing::Value);
        assert!(!matches!(
            ResourceMode::Value.host_passing(),
            HostPassing::TakeOwned
        ));
    }

    #[test]
    fn shared_type_parser_handles_optional_and_callable_types() {
        let ty: Type = parse_quote!(Option<VmCallable<fn(VmMap) -> VmMap>>);
        assert_eq!(
            type_label(&ty).unwrap(),
            "fn(map) -> map | null",
            "the shared parser is the schema source for both generators"
        );
        assert_eq!(
            parameter_type_label(&ty).unwrap(),
            ("fn(map) -> map | null".into(), true)
        );
    }

    #[test]
    fn shared_type_parser_labels_resource_wrappers_consistently() {
        for ty in [
            parse_quote!(Resource<FakeResource>),
            parse_quote!(ResourceRef<'_, FakeResource>),
            parse_quote!(ResourceMut<'_, FakeResource>),
        ] {
            assert_eq!(type_label(&ty).unwrap(), RESOURCE_SCHEMA_LABEL);
        }
        let owned: Type = parse_quote!(ResourceOwned<FakeResource>);
        let error = type_label(&owned).unwrap_err();
        assert!(error.contains("input-only"), "{error}");
    }
}
